# Generated by Django 4.2.1 on 2023-08-12 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('T2', 'T2'), ('T3', 'T3'), ('T4', 'T4'), ('T5', 'T5'), ('T6', 'T6'), ('T7', 'T7'), ('CN', 'CN')], max_length=2, verbose_name='Thứ')),
                ('start_period', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15')], max_length=2, verbose_name='Tiết bắt đầu')),
                ('num_period', models.IntegerField(default=3, verbose_name='Số tiết')),
                ('idRoom', models.CharField(max_length=10, verbose_name='Phòng học')),
                ('exam_check', models.BooleanField(default=False, verbose_name='Lịch thi?')),
                ('idCourseClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_course', to='course.courseclass', verbose_name='Mã lớp môn học')),
            ],
            options={
                'verbose_name': 'Lịch học',
                'verbose_name_plural': 'Lịch học',
            },
        ),
    ]
