# Generated by Django 4.2.4 on 2023-08-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_std', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile_std',
            old_name='sexStd',
            new_name='genderStd',
        ),
        migrations.RemoveField(
            model_name='profile_std',
            name='stt',
        ),
        migrations.AddField(
            model_name='profile_std',
            name='graduate',
            field=models.BooleanField(choices=[(True, 'Chưa tốt nghiêp'), (False, 'Đã tốt nghiệp')], default=True, verbose_name='Tình trạng tốt nghiệp'),
        ),
        migrations.AddField(
            model_name='profile_std',
            name='identityStd',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='CCCD/CMND'),
        ),
        migrations.AddField(
            model_name='profile_std',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
