# Generated by Django 4.2.4 on 2023-08-19 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_std', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile_std',
            old_name='idFacultyClass',
            new_name='idClass',
        ),
    ]
