# Generated by Django 4.2.1 on 2023-08-12 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_std', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('idSemester', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Mã học kỳ')),
                ('nameSemester', models.CharField(max_length=30, verbose_name='Học kỳ')),
                ('startdateSem', models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu')),
                ('enddateSem', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc')),
            ],
            options={
                'verbose_name': 'Học kỳ',
                'verbose_name_plural': 'Học kỳ',
            },
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('idSub', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Mã học phần')),
                ('nameSub', models.CharField(max_length=70, verbose_name='Tên học phần')),
                ('creditsnum', models.IntegerField(default=0, verbose_name='Số tín chỉ')),
            ],
            options={
                'verbose_name': 'Học phần',
                'verbose_name_plural': 'Danh sách học phần',
            },
        ),
        migrations.CreateModel(
            name='std_sub',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('idClass', models.CharField(max_length=10, verbose_name='Mã lớp')),
                ('progress_grade', models.FloatField(default=0, verbose_name='Điểm quá trình')),
                ('final_grade', models.FloatField(default=0, verbose_name='Điểm kết thúc')),
                ('overall_grade', models.FloatField(default=0, verbose_name='Điểm tổng kết')),
                ('overall_grade_4', models.FloatField(default=0, verbose_name='Hệ số 4')),
                ('overall_grade_text', models.CharField(blank=True, max_length=2, verbose_name='Điểm chữ')),
                ('stt_pass', models.BooleanField(choices=[(True, 'Đạt'), (False, 'Chưa đạt')], default=False, verbose_name='Đạt')),
                ('idStd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_std.profile_std', verbose_name='MSSV')),
                ('idSub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.subject', verbose_name='Mã học phần')),
            ],
            options={
                'verbose_name': 'Điểm',
                'verbose_name_plural': 'Bảng điểm',
            },
        ),
        migrations.CreateModel(
            name='courseClass',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('idClass', models.CharField(max_length=10, verbose_name='Mã lớp')),
                ('startdateCourse', models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu')),
                ('enddateCourse', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc')),
                ('idCourse', models.CharField(blank=True, max_length=3, null=True, verbose_name='Khóa')),
                ('idSemester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.semester', verbose_name='Học kỳ')),
                ('idSub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.subject', verbose_name='Mã học phần')),
            ],
            options={
                'verbose_name': 'Lớp',
                'verbose_name_plural': 'Lớp học phần',
            },
        ),
    ]
