# Generated by Django 4.2.4 on 2023-08-19 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='idDeparment',
            new_name='idDepartment',
        ),
    ]
