# Generated by Django 4.2.4 on 2023-08-19 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_rename_iddeparment_department_iddepartment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facultyclasses',
            old_name='idFacultyClass',
            new_name='idClass',
        ),
    ]
