# Generated by Django 4.2.4 on 2023-08-21 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_rename_idfacultyclass_facultyclasses_idclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='idCourse',
            fields=[
                ('idCourse', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Mã khóa')),
                ('nameCourse', models.CharField(max_length=20, verbose_name='Niên khóa')),
            ],
            options={
                'verbose_name': 'Niên khóa',
                'verbose_name_plural': 'Niên khóa',
            },
        ),
        migrations.AlterField(
            model_name='facultyclasses',
            name='idCourse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.idcourse', verbose_name='Khóa'),
        ),
    ]
