# Generated by Django 4.2.4 on 2023-08-21 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_idcourse_alter_facultyclasses_idcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyclasses',
            name='idCourse',
            field=models.CharField(max_length=2, verbose_name='Khóa'),
        ),
    ]
