# Generated by Django 4.2.4 on 2023-08-21 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_alter_facultyclasses_idcourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultyclasses',
            name='faculty',
        ),
        migrations.AlterField(
            model_name='facultyclasses',
            name='idCourse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.idcourse', verbose_name='Khóa'),
        ),
    ]
